from pathlib import Path

KALSHI_API_BASE = "https://api.elections.kalshi.com/trade-api/v2"

DATA_DIR = Path("data")
RAW_MARKETS_DIR = DATA_DIR / "raw_markets"
RECENT_MARKETS_FILE = DATA_DIR / "recent_markets.json"
DECISIONS_LOG_FILE = DATA_DIR / "log.json"
OUTCOMES_LOG_FILE = DATA_DIR / "outcomes.json"
PAPER_TRADES_LOG_FILE = DATA_DIR / "paper_trades.json"

REQUEST_TIMEOUT_SECONDS = 15
MARKET_PAGE_LIMIT = 1000
MAX_MARKET_PAGES = 3
MAX_MARKET_PAGES_WITH_SHORT_HORIZON = 8

SCAN_LIMIT = 10
SHORT_HORIZON_SIGNAL_SHARE = 0.8
SHORT_HORIZON_MIN_MARKETS = 75
EXCLUDE_SYNTHETIC_MARKETS = True
EXCLUDED_EVENT_TICKER_KEYWORDS = ("MENTION", "WORDCOUNT")
EXCLUDED_EVENT_TICKER_PREFIXES = ("KXETH15M", "KXBNB15M")
PENALIZED_EVENT_TICKER_PREFIXES = {"KXSOL15M": 12}
MIN_LIQUIDITY_CENTS = 0
MIN_SNAPSHOT_ORDERBOOK_SIZE = 1
MIN_VOLUME = 1000
MIN_ORDERBOOK_SIZE = 25
MAX_PRICE_TO_BUY_YES = 40
MIN_PRICE_TO_BUY_NO = 60
EXCLUDE_PROVISIONAL = True
SLEEP_TIME = 600
SLEEP_TIME2 = 300

PAPER_TRADING_ENABLED = True
PAPER_MAX_TRADES_PER_RUN = 3
PAPER_MIN_SCORE = 80
PAPER_MAX_ENTRY_PRICE = 75
PAPER_STARTING_BANKROLL_DOLLARS = 100
PAPER_POSITION_SIZE_DOLLARS = 15
PAPER_POSITION_SIZE_FLOOR_RATIO = 0.2
PAPER_MAX_CAPITAL_UTILIZATION = 0.8
PAPER_PREFERRED_MAX_HOLD_HOURS = 24
PAPER_MAX_LONG_EXPIRY_SHARE = 0.2
PAPER_TAKE_PROFIT_PARTIAL_PCT = 1.0
PAPER_TAKE_PROFIT_FULL_PCT = 2.0
